# Generated by Django 5.1.2 on 2024-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizparticipant',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
